### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Amxx** [iExecBlockchainComputing/dataprotector-sdk#186]

**Comment by Amxx** [comment]
[For order management, instead of using one order per operation, with custom salt, and thus a custom hash, that needs to be signed](https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/new-sc-for-app-workflow/packages/sharing-smart-contract/contracts/ManageOrders.sol#L89-L104), you could do:

```solidity
   function createAppOrder(
        address _appAddress
    ) internal returns (IexecLibOrders_v5.AppOrder memory) {
        //create AppOrderOperation
        IexecLibOrders_v5.AppOrderOperation memory appOrderOperation = IexecLibOrders_v5
            .AppOrderOperation({
                order: IexecLibOrders_v5.AppOrder({
                    app: _appAddress,
                    appprice: 0,
                    volume: type(uint256).max,
                    tag: TAG,
                    datasetrestrict: address(0), // check is enforced by the requester, which is whitelisted
                    workerpoolrestrict: address(0), // check is enforced by the requester, which is whitelisted
                    requesterrestrict: address(this), // this
                    salt: bytes32(0),
                    sign: new bytes(0)
                }),
                operation: IexecLibOrders_v5.OrderOperationEnum.SIGN, //OrderOperationEnum
                sign: new bytes(0)
            });

        // presign - no-opp if the order was already signed
        _pocoDelegate.manageAppOrder(appOrderOperation);

        return appOrderOperation.order;
    }
```
This would mean:
- A single order per ressource (app or dataset)
- Once its signed, its good. All usage go in the same counter → less storage touched
- Check/persmission is enforced by the ProtectedDataSharing contract, no need to re-check in the PoCo
- infinite volume is safe, order is only valid as long as the `ProtectedDataSharing` owns the ressource and does the request.

This works for app and dataset.

**Comment by Amxx** [comment]
If we are smart, this order could be built and pre-signed when the app takes ownership of the asset (app or dataset). That way you don't have to re-do the `_pocoDelegate.manageAppOrder` when you want to match a new request order.

**Comment by Amxx** [comment]
[Line 220 seems to be duplicated](https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/new-sc-for-app-workflow/packages/sharing-smart-contract/contracts/ProtectedDataSharing.sol#L220-L221)

**Comment by Amxx** [comment]
Opinionated design proposition:
- remove `removeCollection`
- inherit from `ERC721BurnableUpgradeable` → adds a `burn` function that does the same as `removeCollection`
- override `_update(...)`
```solidity
function _update(address to, uint256 tokenId, address auth) internal virtual override returns (address) {
    if (to == address(0) && collectionDetails[_collectionTokenId].size > 0) {
        revert CollectionNotEmpty(_collectionTokenId);
    }
    return super._update(to, tokenId, auth);
}
```
This would protect against calling internal `_burn` on a collection that is not empty

**Comment by Amxx** [comment]
[Line 312 only support `getApproved`, it should also support `isApprovedForAll`](https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/new-sc-for-app-workflow/packages/sharing-smart-contract/contracts/ProtectedDataSharing.sol#L312).

Line 319 will check that `address(this)` is authorized anyway, so I would simply remove line 312.

**Comment by Amxx** [comment]
It would be cleaner to do line 319 (take custody of the asset) then do all storage change (line 318, 320, ...). Do sure there is a risk, but it would be good practice.

I would swap line 318 and 319

**Comment by Amxx** [comment]
same, in `removeProtectedDataFromCollection`, I would change the state (lines 341 and 342) BEFORE doing the transferFrom (line 336)

**Comment by Amxx** [comment]
`_safeTransferFrom` is only used once. Other places use `_protectedDataRegistry.safeTransferFrom` directly. Consider removing `_safeTransferFrom`.

**Comment by Amxx** [comment]
`subscribeTo` uses `collectionDetails[_collectionTokenId]` many time. It should be cached (using a storage pointer)

**Comment by Amxx** [comment]
```solidity
uint48 endDate = uint48(block.timestamp) +
    collectionDetails[_collectionTokenId].subscriptionParams.duration;
collectionDetails[_collectionTokenId].subscribers[msg.sender] = endDate;
if (collectionDetails[_collectionTokenId].lastSubscriptionExpiration < endDate) {
    collectionDetails[_collectionTokenId].lastSubscriptionExpiration = endDate;
}
```
can be rewritten as
```solidity
collectionDetails[_collectionTokenId].subscribers[msg.sender] = Math.max(
    collectionDetails[_collectionTokenId].subscribers[msg.sender],
    block.timestamp + collectionDetails[_collectionTokenId].subscriptionParams.duration
).toUint48();
```

Also, I find it strange that if I still have 3 days of subscription left, and if I pay for 1 month of subscription, the 3 days I have are lost. I should have 1month + 3days.

**Comment by Amxx** [comment]
In `removeProtectedDataFromSubscription`, you can remove the `_collectionTokenId` from the arguments, and read it from the protectedData details

**Comment by Amxx** [comment]
### `subscribeTo` can be frontrun

The collection manager can front run a call to `subscribeTo` (by a user), to set the duration to 1 second, while keeping the same price.

This will drain take the funds from the user just the same, but not give him a subscription. 

A fix would be :
- user says how long he wants to subscribe for
- user give the funds for that
- smart contract that the duration asked + value passed match the current price
- if collection manager increassed the price, the transaction revert and no funds are spent by the user.
- if collection manager decreassed the price, user gets a partial refund 

This would allow removing the duration argument. Renting price would be "per day" or similar.
You could have a security check that the user never subscribe for more than X (1 month ? 1 year?)

**Comment by Le-Caignec** [comment]
The goal was to safeguard the interests of both the collection owner and the end user in a manner that ensures mutual protection. To achieve this, the system was designed with specific mechanisms:

- Protection for the Collection Owner: The system safeguards collection owners by allowing them to retain control over their datasets. Owners specify both the duration and the price for accessing the dataset, ensuring that they can regain ownership of their data after the rental period. An end user could not rent/subscribe a dataset for an "infinite" period. Indeed, if an end user chooses to extend the rental period by renting the dataset again, these periods are not cumulative, ensuring that the collection owner's rights are preserved. This setup prevents perpetual loss of control over their dataset.

- Protection for the End User: The system also protects end users by ensuring that they have uninterrupted access to the rented or subscribed datasets throughout the agreed-upon time period. This means the collection owner cannot revoke access to the data during the active rental period, thereby guaranteeing that the end user can fully utilize the data they have paid for without unexpected restrictions.

**Comment by Amxx** [comment]
About `AppWhitelist.sol`

Is it really necessary to check that the owner of the app is the `ProtectedDataSharing` contract ? I think its irrelevant. An app is safe by its design, not because of its owner. 

- The `ProtectedDataSharing` will not be able to any app that it doesn't own.
- The App may be whitelisted, then removed from `ProtectedDataSharing` ... and it would still be witelisted.

Also: address(this) in the event is not usefull.

You could simplify the contract as:
```solidity
contract AppWhitelist is IAppWhitelist, Ownable {
    mapping(address => bool) public appWhitelisted;

    constructor(address _owner) Ownable(_owner) {}

    function addApp(address _app) public onlyOwner {
        appWhitelisted[_app] = true;
        emit NewAppAddedToAppWhitelist(_app);
    }
}
```

If you wanted to be really smart about it, you'd use ERC734 so that this contract is actually a PoCo whitelist.
```solidity
contract ERC734 {
    mapping(bytes32 => mapping(uint256 => bool)) private _purposes;
    
    event KeyUpdated(bytes32 id, uint256 purpose, bool id);

    function keyHasPurpose(bytes32 id, uint256 purpose) public view returns (bool) {
        return _purposes[id][purpose];
    }

    function _setKeyHasPurpose(bytes32 id, uint256 purpose, bool value) internam {
        _purposes[id][purpose] = value;
        emit KeyUpdated(id, purpose, value);
    }
}

contract Whitelist is Ownable, ERC734 {
    uint256 internal constant GROUPMEMBER_PURPOSE = 4;
    
    constructor(address initialOwner) Ownable(initialOwner) {}

    function add(address ressource) public onlyOwner {
        _setKeyHasPurpose(bytes32(uint256(ressource)), GROUPMEMBER_PURPOSE, true);
    }
}
``` 
then

**Comment by Amxx** [comment]
In `DataProtectorSharing`, `_appRegistry` is set but never used

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/new-sc-for-app-workflow/packages/sharing-smart-contract/contracts/registry/AppWhitelistRegistry.sol#L56-L61 could be significantly cheaper by using clones

**Comment by Amxx** [comment]
I get that having a whitelist factory is a nice touch. That is easier to work with than deploying your own smart contract.

But assuming someone wants to deploy its own smart contract, why should he not be able to do so ? What is the risk here? I'm not sure I see the point of having to verify that the whitelist was created by the whitelist registry. Also its not a registry since all whitelists are ownable and the registry is not really involved in ownership (unlike appRegistry/datasetRegistry/...)

**Comment by Amxx** [comment]
Who managed the app whitelist for a dataset? If the dataset is sold, the owner of the corresponding whitelist keeps tremendous power (he could whitelist an app that leaks the data).

**Comment by Le-Caignec** [comment]
fix on this [PR](https://github.com/iExecBlockchainComputing/dataprotector-sdk/pull/179)
