### ISSUE TITLE
Review 2024/03/24

### ISSUE THREAD

**Issue by Amxx** [iExecBlockchainComputing/dataprotector-sdk#207]
[_checkConsumeProtectedData](https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L115-L118) returns 2 boolean. By construction at least one is true (both could be true), otherwize the function revert. The second boolean is never checked, because its assumed to be the negation of the first one.

Current usage of that function shows that it could be simplified to avoid unecessary operations:

```
    function _checkConsumeProtectedData(
        address _protectedData,
        IexecLibOrders_v5.WorkerpoolOrder calldata _workerpoolOrder
    ) internal view returns (mode) {
        if (_workerpoolOrder.workerpoolprice > 0) {
            revert WorkerpoolOrderNotFree(_workerpoolOrder);
        }

        // check voucherOwner == msg.sender
        // check voucher isAuthorized(this)
        ProtectedDataDetails storage _protectedDataDetails = protectedDataDetails[_protectedData];
        uint256 collectionTokenId = _protectedDataDetails.collection;
        if (_protectedDataDetails.renters[msg.sender] >= block.timestamp) {
            return mode.RENTING;
        } else if (collectionTokenId != 0 &&  _protectedDataDetails.inSubscription && collectionDetails[collectionTokenId].subscribers[msg.sender] >= block.timestamp) {
            return mode.SUBSCRIPTION;
        } else  {
            revert NoValidRentalOrSubscription(collectionTokenId, _protectedData);
        }
    }
```

**Comment by Amxx** [comment]
Remove [usage of console](https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L33)

**Comment by Amxx** [comment]
Avoid building full `XxxOrderOperation` unless necessary
```solidity
    function _createAppOrder(
        address _appAddress
    ) internal view returns (IexecLibOrders_v5.AppOrder memory) {
        //create AppOrderOperation
        return IexecLibOrders_v5.AppOrder({
            app: _appAddress,
            appprice: 0,
            volume: type(uint256).max,
            tag: TAG,
            datasetrestrict: address(0),
            workerpoolrestrict: address(0),
            requesterrestrict: address(this), // this
            salt: bytes32(0),
            sign: new bytes(0)
        });
    }

    function _createPreSignAppOrder(
        address _appAddress
    ) internal returns (IexecLibOrders_v5.AppOrder memory) {
        IexecLibOrders_v5.AppOrder memory order = _createAppOrder(_appAddress);

        _pocoDelegate.manageAppOrder(IexecLibOrders_v5.AppOrderOperation({
            order: order,
            operation: IexecLibOrders_v5.OrderOperationEnum.SIGN, //OrderOperationEnum
            sign: new bytes(0)
        });

        return order;
    }
```

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L224

Are native token in bellecour not nRLC? there is a decimal shift ?

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L274 can be slightly simplified

```
appWhitelistRegistry.ownerOf(uint256(uint160(address(_appWhitelist))));
```

**Comment by Amxx** [comment]
In an ideal world, https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L267-L271 would be a receive hook. That would enable operator for a dataset to add it to a collection (and not restrict that to the owner only)

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L275-L276

```diff
-        uint256 tokenId = uint256(uint160(_protectedData));
-        _protectedDataRegistry.safeTransferFrom(msg.sender, address(this), tokenId);
+        _protectedDataRegistry.safeTransferFrom(msg.sender, address(this), uint256(uint160(_protectedData)));
```

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L317-L321

Faire ca est significativement plus cher que de forward la value dirrectement.

Ca me demande. Pourquoi l'user paye en native currency (rlc) et le proprietaire de la collection est payé en ERC20 (sRLC) ? Ca aurait pas du sens d'utiliser la même chose partout. Sois tu fait tout en RLC, soit tout en sRLC ... mais j'éviterai les deposit for a la volé

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L332-L340

```solidity
_pocoDelegate.transferFrom(msg.sender, ownerOf(_collectionTokenId), price);
```

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L348-L351

le cas == 0 est vraiment necessaire ? On a deja `_collectionDetails.subscriptionParams.duration != _duration` ... a ce compte ca si vous voulez vraiment check, faites

```solidity
        if (duration != _collectionDetails.subscriptionParams.duration || duration == 0) {
```

**Comment by Amxx** [comment]
same question as last time:
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L361-L367

If I subscribe now for 3 weeks, and I re-substribe in 2 weeks. 
- I'll be paying the full, prive for 3 weeks
- I'll vget 3 weeks starting when at `block.timestamp`
- I still had 1 week remaining that get lost

User are insentivised to not renew until their subscription is fully exprired. I don't thinbk that is a good model.

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L388

If you are removing one protected data from the subscription, do you really want to remove the subscription details for the entire collection?

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L388

and 

https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L423-L431

Same as before. You don't need go do the encoding yourself. WTF

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L440-L442

same as before

**Comment by Amxx** [comment]
If someone calls `rentProtectedData` or `rentProtectedDataWithAccount`, this can be frontrun by the owner. By doing `setProtectedDataToRenting`, the owner can change the price/duration, and the user will pay the new price (if using ...WithAccount) and get the new duration, even if the duration is 1second.

**Comment by Amxx** [comment]
Similarly, if someone calls `buyProtectedDataForCollection`, the owner can frontrun to change the price the price

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L523-L527

Like the other `WithAccount` this function uses sRLC for the payments. It should not be payable, and the check on line 528 should be removed.

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L530-L542

This doesn't look right

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L508-L520

No msg.value check here. I could pay 0 and that would be ok.

**Comment by Amxx** [comment]
https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L582

That is not the correct price to use.

**Comment by Le-Caignec** [comment]
Fix in this [PR](https://github.com/iExecBlockchainComputing/dataprotector-sdk/pull/201)

**Comment by PierreJeanjacquot** [comment]
> https://github.com/iExecBlockchainComputing/dataprotector-sdk/blob/feature/inetegrate-iexec-account/packages/sharing-smart-contract/contracts/DataProtectorSharing.sol#L224
> 
> Are native token in bellecour not nRLC? there is a decimal shift ?

yes native is 10**18
