### ISSUE TITLE
Webpacking this package causing issues

### ISSUE THREAD

**Issue by agourdelFF** [iExecBlockchainComputing/dataprotector-sdk#60]
Hi again @PierreJeanjacquot ,
We met an other issue.
The fact that the package is webpacked when it built is causing a lot of issues in our Website Project.
(version mismatch issues for example)
So our question is "Do you really need to use webpack?"

It's pretty rare to find a low-level package as your, using webpack whereas the package can be used in any kind of context (as back context for example) 
And the choice to bundle the sources is more often let to the final user/Developer .

What do you think ?

**Comment by PierreJeanjacquot** [comment]
Hi @agourdelFF 
The package requires many crypto dependencies relying on nodejs builtins, so consuming it in a browser can be tricky.
Having the smallest setup possible for the user was a strong requirement when the project was initialized.
Using a bundle packaging nodejs builtins polyfills was primarily selected as an option to make things work out of the box for the majority of the projects at the cost of some other issues.

On my side, I'm not a big fan of this solution and I agree with you
> the choice to bundle the sources is more often let to the final user/Developer .

Now we are still early in the development of this project and your feedback has a lot of value for us.
Can you give us more details about the context in which you're trying to use the lib (framework, other libs, bundler...) and the exact issues you have?

**Comment by agourdelFF** [comment]
@PierreJeanjacquot 
Thanks for your reply.

`In case you want to experiment without the bundle, you can tweak the package.json to use ./dist/index.js instead of ./dist/bundle.js`

I already try this one but it raises some new errors.  The packages @multiformats/multiaddr kubo-rpc-client strtok3 are not found even if they are installed. (I didn't go any further in that direction because I know when I start, I don't know when I finish)

Our Context :
Francis Otshudi  from your organization ask us to build a demo using the package dataProtector  In order to allow you to make a demonstration at your next presentation.

As deadlines are tight and resources are scarce, we choose to directly include this demo (A simple web page using your package) in our front app of our business 'https://ziplo.fr/' 
Our front app is a nuxt/vue application. And the issue is easy. The version of webpack that you are using to bundle the package is too high compares to ours. (When we compil the app, our loader think that the bundle.js is a binary file...) Our version of webpack is linked to our version of nuxt. So we can't/don't want to upgrade all the stuff. 

I wrote to you to keep you inform of all the context but we also inform Francis that we have some issues. 

I think I will create a tee shirt : "DO NOT WEBPACKED YOUR PACKAGES IF YOU'RE NOT THE FINAL USER"

**Comment by PierreJeanjacquot** [comment]
Hi @agourdelFF

You may already have some information from @Fran6o but here is the last update.

We are currently working on a version without bundle, you can follow this PR #62 
There is still some limitation on polyfills we want to address on our side but you can already use the nightly build of the library `0.1.1-nightly-39c70d6ed67ca78afc10185ff839f0fbdcf77100`

Install

```sh
npm i @iexec/dataprotector@0.1.1-nightly-39c70d6ed67ca78afc10185ff839f0fbdcf77100
```

Prerequisites

- the bundler must support conditional exports resolution
- the bundler must provide polyfills for `node:buffer` and `node:stream`

Here is integration example with webpack@5 you can use to add the polyfills (conditional exports is already supported by webpack@5)

```sh
npm i -D buffer readable-stream
```

```js
// webpack.config.cjs
const webpack = require('webpack');

module.exports = {
  // ... other stuff goes here
  plugins: [
    // polyfill 'node:buffer' and 'node:stream' used by file-type
    new webpack.NormalModuleReplacementPlugin(/node:/, (resource) => {
      const mod = resource.request.replace(/^node:/, '');
      switch (mod) {
        case 'buffer':
          resource.request = 'buffer';
          break;
        case 'stream':
          resource.request = 'readable-stream';
          break;
        default:
          throw new Error(`Not found ${mod}`);
      }
    }),
  ],
};
```

Also the issue you run into (`@multiformats/multiaddr` `kubo-rpc-client` `strtok3` not found) is probably related to these packages having dropped support for the legacy entry point definition (`"main"` or `"module"`) in favor of `"exports"`.
I'm afraid you will have to deal with the resolution configuration on your side if your bundler is a bit outdated.

**Comment by agourdelFF** [comment]
Hi @PierreJeanjacquot ,
Thanks for your explanation. I tryed but at the end, I still had the  (@multiformats/multiaddr kubo-rpc-client strtok3 not found) because using "exports" in their respective package.json

BUT

I was tired of this so I found an other way :
I git cloned the main branch of the dataProtector project in a folder elsewhere in my computer.
I 'NPM RUN BUILD' it .
I copied the bundle.js
I pasted it in my /static folder
And I import it like we use to do in the good old days (<script src="/static/js/bundle.js">)

IT WORKS.

This is not conventional but for a demo it will be enough !
Thanks for you time.

**Comment by PierreJeanjacquot** [comment]
Hi @agourdelFF thank you for the update,

Not everything was good in the old days :rofl: 
Your issue is interesting, we may need to provide the bundled version anyway for this kind of usage without exporting it as the package entry point.

Can you try to pull directly the package from unpkg.com rather than building it on your own?

```html
<script src="https://unpkg.com/@iexec/dataprotector@0.1.1/dist/bundle.js">
```

**Comment by agourdelFF** [comment]
Hi @PierreJeanjacquot 
Y  a un tchat sur lequel on peut échanger ? 
J'ai d'autres questions mais sur la mécanique interne cette fois de tout Iexec.

**Comment by PierreJeanjacquot** [comment]
Discord is currently the preferred channel, @luisccastillo should be able to answer most of your questions and I could give a look at some specific topics.

**Comment by 0xRomain** [comment]
Hi @PierreJeanjacquot @agourdelFF 
We figured out how to make it work with Next.JS following your recommendations, Thank you!
This is the commit with the updates: https://github.com/TalentLayer-Labs/indie-frontend/pull/94/commits/dee81fac4aaf59ad5c76b21aa7dfad78eb32e14b

**Comment by PierreJeanjacquot** [comment]
Thank you for your feedback @0xRomain

**Comment by PierreJeanjacquot** [comment]
closing this as the package is now provided without pre-bundling
